import { Injectable } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { randomUUID } from "crypto";
import { mkdir, readFile, writeFile } from "fs/promises";
import { join, resolve } from "path";
import { StorageProvider, StoredFile } from "../storage-provider.interface";

/**
 * Dev/local stand-in for S3. Files live outside the web root, under
 * UPLOAD_DIR (default ./uploads) — nothing serves this directory statically,
 * so the only way to read a file back is through AttachmentsController's
 * authorization-checked download route (blueprint §15: "no attachment is
 * ever served from a public URL").
 */
@Injectable()
export class LocalDiskStorageProvider implements StorageProvider {
  private readonly root: string;

  constructor(config: ConfigService) {
    this.root = resolve(config.get<string>("UPLOAD_DIR") ?? "./uploads");
  }

  async save(buffer: Buffer, opts: { extension: string }): Promise<StoredFile> {
    await mkdir(this.root, { recursive: true });
    const storageKey = `${randomUUID()}${opts.extension}`;
    await writeFile(this.safePath(storageKey), buffer);
    return { storageKey };
  }

  async read(storageKey: string): Promise<Buffer> {
    return readFile(this.safePath(storageKey));
  }

  /** storageKey is generated by us (never user input) but this stops any path traversal by construction. */
  private safePath(storageKey: string): string {
    const path = join(this.root, storageKey);
    if (!path.startsWith(this.root)) {
      throw new Error("Invalid storage key");
    }
    return path;
  }
}
